services:
    web:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./storage:/storage
        environment:
            - ASPNETCORE_ENVIRONMENT=Release
            - ASPNETCORE_URLS=https://+443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/localhost.pfx
        depends_on:
            - oracle_db
            - sql_server_db
    oracle_db:
        image: truevoly/oracle-12c:latest
        # volumes:
        #     - /home/oracle/oradata:/u01/app/oracle 
        ports:
            - "1521:1521"
            - "5500:5500"
            - "8080:8080"
        environment:
            - DBCA_TOTAL_MEMORY=2048
    sql_server_db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password123